// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import TableOutlined from 'D:/Projects/register-admin-h5/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { TableOutlined };
